apiVersion: apps/v1
kind: Deployment
metadata:
  name: timesheet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timesheet
  template:
    metadata:
      labels:
        app: timesheet
    spec:
      containers:
        - name: timesheet
          image: souissiamine001/timesheet-devops:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
